version: "3.9"

services:
  app:
    build:
      context: .
      target: development
      args:
        NODE_ENV: local
    environment:
      - HOME=/tmp
      - APP_ENV=${APP_ENV:-dev}
      - NODE_ENV=local
    volumes:
      - "./:/srv/app:rw"
    user: "${DEV_UID:-1000}:${DEV_GID:-1000}"
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - default
  ngrok:
    image: ngrok/ngrok:latest
    command:
      - "http"
      - "http://host.docker.internal:80"
    environment:
      NGROK_AUTHTOKEN: <YOUR TOKEN HERE>
    ports:
      - 4040:4040
networks:
  default: ~
